### ISSUE TITLE
Revise the Composition Profile

### ISSUE THREAD

**Issue by gcangioli** [hl7-eu/laboratory#10]

**Comment by gcangioli** [comment]
Some questions to be addressed:

- [ ] should be this a profile of Clinical Document or of Composition ?
reason for not have this derived from "Clinical Document" is to allow more flexibility for the subject (not restricted to Patient | Group | Location | Device)
- [ ] should the type be a fixed value (as used in several countries) ?
- [ ] should we add category ? (likely needed if type not fixed)
- [ ] should we add details about the Encounter ?
- [ ] any further detail about the event ? e.g. suggested value set for code 
- [ ] any further detail about the attester ?
- [ ] are you fine with the proposed section slices ?
- [ ] are you good with the basedOn-order-or-requisition extension ?
- [ ] how to map / deal with composition status and DiagnosticReportStatus ?

**Comment by Espen64** [comment]
In the HL7 FHIR v4 I found the following description of a composition resource:

- The composition section defines a section (or sub-section) of the document, but unlike CDA, the section entries are actually references to other [resources](https://build.fhir.org/resourcelist.html) that hold the supporting data content for the section. This design means that the data can be reused in many other ways.

- Unlike CDA, the context defined in the Composition (the subject, author, event, event period and encounter) apply to the composition and do not specifically apply to the resources referenced from the section.entry. T**here is no context flow model in FHIR, so each resource referenced from within a Composition expresses its own individual context**. In this way, clinical content can safely be extracted from the composition

My question is, how can we add a legal authentication or author on composition (the CDA document) when there is no direct link between the composition resource and the resources (entries) linked? Whould this not be come a Challenge for the legal authenticator of the composition?

**Comment by gabriel0316** [comment]
We have to differentiate between a single composition and its related resources and a composition within a FHIR document. Within a FHIR document we should not have a problem regarding the various actors because all information is gathered within a Bundle resource resulting in immutable information. 

However, if we want to use FHIR resources on their own outside of the scope of a FHIR document the situation is completely different because we change from a document paradigm to a resource oriented paradigm. So, for those resource that have been created based on a CDA document we would have to specify which information is necessary to clarify the context of a single resource (e.g. an Observation) - probably we would need Provenance resources. For those resource that have been created solely in the FHIR context we have to clarify how they have to be "signed".

**Comment by gcangioli** [comment]
https://github.com/hl7-eu/laboratory/commit/0853cd2225bfa70ba4815b038dfa69689c3a4d1c
