### ISSUE TITLE
Consolidate the general report structure

### ISSUE THREAD

**Issue by gcangioli** [hl7-eu/laboratory#2]
Consolidate the proposed structural approach preserving the duality of FHIR document and diagnosticReport

**Comment by gcangioli** [comment]
The proposed approach tries to balance on one hand the expectation to have all the different types of documents (summaries, diagnostic reports, other reports,... ) represented by using the same approach, to facilitate also the mapping from the existing CDA documents. On the other side the fact that HL7 FHIR introduced a specific resource for diagnostic reports the _DiagnosticReport_ (and only for this kind of documents) that is expected to be used by several FHIR based systems for managing diagnostic reports' information.

The solution proposed has been that of **using a signable document bundle** (a FHIR Document) **including include also the _DiagnosticReport_ resource.**

**Advantage**: 
- preserve the FHIR document and diagnosticReport duality

**Disavantage**: 
- potential duplication of information in Composition and DiagnosticReport (a little more work for creators)

**Comment by gcangioli** [comment]
**To be discussed:**

- [ ] Should or shall include a diagnosticReport ?
- [ ] Should we rely on the information that are in the composition or to have them duplicated in the diagnostciReport ?
- [ ] The diagnosticReport is included in the  bundle by using a reverse relationship DiagnosticReport  Composition; done with a R5 extension (I,e the composition element added in R5) . This mean that we are pre-adopting a R5 rule, while R4 requests that data in the bundle has to be referenced from the composition down (with the exception of Provenance). Do you agree with this approach that can bring to warnings when the Bundle is validated ?

**Comment by rhausam** [comment]
I agree we need to discuss and resolve those items - ideally before going too much farther.  I have some additional comments/questions on the particular items:

> Should or shall include a diagnosticReport ?
Yes, we need to decide if the DiagnosticReport in the Bundle should be 0..1 or 1..1.

> Should we rely on the information that are in the composition or to have them duplicated in the diagnostciReport ?
Have we figured out the list of which elements are actually duplicated between DiagnosticReport and Composition (I haven't actually tried to do that yet)?  The elements that are resource references don't matter, as the content isn't actually duplicated.

> The diagnosticReport is included in the bundle by using a reverse relationship DiagnosticReport  Composition; done with
> a R5 extension (I,e the composition element added in R5) . This mean that we are pre-adopting a R5 rule, while R4
> requests that data in the bundle has to be referenced from the composition down (with the exception of Provenance). Do 
> you agree with this approach that can bring to warnings when the Bundle is validated ?
I think the R5 "rule" is actually mostly a clarification, rather than an actual change.  From the conversations that we had, I think it mainly comes down to Grahame Grieve agreeing to modify his interpretation so that it least more closely is aligned with what Lloyd McKenzie had been thinking was allowed all along (references between the included resource and the Bundle that could be made in either direction).  So, in my opinion at this point, we should be on pretty safe ground to adopt in R4(B) the R5 extension that references Bundle from Composition.  I agree that there may still (at least for a while) be some IG Publisher warnings about this.  But I expect that this would be rather readily explainable and shouldn't cause any significant problems with approval of the IG for publication (and I'm not sure of all of the details of the process for European FHIR IG publications).

> Should we create a single generic Bundle profile or have also specialized profiles for different kinds of lab reports ?
There may be some potential usefulness for doing this, but I'm not sure if or how much it would be needed.  It would depend on the specific specializations being considered (e.g., something like microbiology, genomics), I think.
 
> Have you any other comment on the current Bundle profile ?
I don't have any further comments at the moment.

**Comment by gcangioli** [comment]
> Have we figured out the list of which elements are actually duplicated between DiagnosticReport and Composition? I haven't actually tried to do that yet. The elements that are resource references don't matter in this case, as the content isn't actually being duplicated (multiple references to the same resource are fine).

good catch... created a new issue #11

**Comment by gabriel0316** [comment]
Regarding the question if we shall include the DiagnosticReport as 0..1 or 1..1 we have to discuss the use cases this FHIR IG is supposed support.

Furthermore, I'm raising the question about the FHIR version that this IG is based on. Why is it R4?

**Comment by gcangioli** [comment]
> Furthermore, I'm raising the question about the FHIR version that this IG is based on. Why is it R4?

Because several current implementations are based on R4, I'm aware about R4b/R5 only in the Pharma regulatory space.

We should consider R5 if there are reasons for moving in this direction.
Nothing however prevent us - when the work on R4 is done - to make also a R5 version of this guide.

**Comment by rhausam** [comment]
I think it may be useful to consider whether we should work on R4B and R5 versions simultaneously.  As I expect we probably all are aware, R5 (5.0.0) is now the default FHIR version - although it is likely that many specifications and implementations will remain on R4/R4B for a considerable period of time (potentially until after R6 is released).  But I think it is a relatively small amount of additional work to do prepare and provide both the R4B and R5 versions simultaneously - and that probably would end up being considerably less additional work overall than doing them sequentially.

**Comment by joofio** [comment]
even though I think we could do R5 after R4B, the dual approach seems better at the moment since it could help us track (potentially breaking) changes between versions that we might overlook unless we actually do the work

**Comment by gcangioli** [comment]
> even though I think we could do R5 after R4B, the dual approach seems better at the moment since it could help us track (potentially breaking) changes between versions that we might overlook unless we actually do the work

Distinct issue created for this topic #12

**Comment by bdc-ehealth** [comment]
General opinion in Belgium is now at the moment to stick with R4 ( R5 might be considered in the future )

**Comment by gcangioli** [comment]
2023-04-13: keep the Diagnostic Report reference to the Composition

**Comment by gcangioli** [comment]
2023-04-13: let's start with the generic profiles and then let's see if we need specialized profiles. There may be in fact some potential usefulness for doing this. It would depend on the specific specializations being considered (e.g., something like microbiology, genomics).
