### ISSUE TITLE
error	Rule eu-lab-1

### ISSUE THREAD

**Issue by lpg-tech** [hl7-eu/laboratory#51]
seems to have an error in rule:
"'At least one of these Observation elements shall be provided: "value", "dataAbsentReason", "hasMember" or "component"' Failedorg.hl7.fhir.exceptions.PathEngineException: Unable to evaluate as a boolean: registered,cancelled (@char 11) (log: org.hl7.fhir.exceptions.PathEngineException: Unable to evaluate as a boolean: registered,cancelled (@char 11))"

**Comment by oliveregger** [comment]
The problem is that in the java fhirpath implementation the or seems to have precedence over the in, if an additional paranthesis is added the invariant is working as expected:

original:
status in ('registered'|'cancelled') or value.exists() or hasMember.exists() or component.exists() or dataAbsentReason.exists()

modified:
(status in ('registered'|'cancelled')) or value.exists() or hasMember.exists() or component.exists() or dataAbsentReason.exists()

will provide a PR for this.

**Comment by oliveregger** [comment]
according to http://hl7.org/fhirpath/N1/#operator-precedence the original should be correct.
